exec(open("dynamics_plotting.py").read())
exec(open("rank_vs_de_plotting.py").read())
exec(open("prediction_accuracy_plotting.py").read())
exec(open("eigenvalues_plotting.py").read())
exec(open("denoising_plotting.py").read())
exec(open("benchmarking_plotting.py").read())
